using System;

namespace Docmind.Api.Models
{
    public class DocumentChunk
    {
        // Unique identifier for this specific text slice inside Qdrant
        public Guid Id { get; set; }

        // Links this chunk back to its parent document ID
        public string DocumentId { get; set; } = string.Empty;

        // Friendly name of the source file (e.g., "HR_Policy.pdf") for UI citation displays  
        public string DocumentName { get; set; } = string.Empty;

        // The actual text payload extracted from the page slice
        public string Text { get; set; } = string.Empty;

        // Tracks the logical position ordering of the slice within the file
        public int ChunkIndex { get; set; }

        // The specific document page number this text was found on
        public int PageNumber { get; set; }

        // Storing as an ISO string format ensures clean text serialization across the database channel
        public string UploadedAt { get; set; } = DateTime.UtcNow.ToString("o");

        // The 768-dimension math coordinate vector generated by nomic-embed-text
        public ReadOnlyMemory<float> Embedding { get; set; }
    }
}